# Generated by Django 3.0.5 on 2021-11-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_auto_20211104_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_url', models.CharField(max_length=10000, unique=True)),
                ('short_url', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='short_urls',
        ),
    ]
